#!/bin/bash

##########################
#                        #
#   The PBS directives   #
#                        #
##########################

# Define the shell in which your jobs should run. Shouldn't really be changed
# unless you have a very specific reason for doing so
#PBS -S /bin/bash


# Define the name for the job
#PBS -N lifting_merging



# Defining the wall time for the job
#PBS -l walltime=6:00:00



#PBS -o /group/tran3/duytran/ngocduy.tran/ncer_scores/output/




# Selecting which queue to send the job to
#PBS -q batch





# Defining the amount of memory you require
#PBS -l mem=12GB




# Define the email address to be used in correspondence
#PBS -M ngocduy.tran@mcri.edu.au


# Define the number of nodes and cores you require
#PBS -l nodes=1:ppn=8



# Used to define which project job is associated with
#PBS -A tran3


### END OF PBS OPTIONS



##########################################
#                                        #
#   Output some useful job information.  #
#                                        #
##########################################

#echo ------------------------------------------------------
#echo -n 'Job is running on node '; cat $PBS_NODEFILE
#echo ------------------------------------------------------
#echo PBS: qsub was run on $PBS_O_HOST
#echo PBS: originating queue is $PBS_O_QUEUE
#echo PBS: executing queue is $PBS_QUEUE
#echo PBS: working directory is $PBS_O_WORKDIR
#echo PBS: execution mode is $PBS_ENVIRONMENT
#echo PBS: job identifier is $PBS_JOBID
#echo PBS: job name is $PBS_JOBNAME
#echo PBS: node file is $PBS_NODEFILE
#echo PBS: current home directory is $PBS_O_HOME
#echo PBS: temporary directory on node is $TMPDIR
#echo PBS: PATH = $PBS_O_PATH
#echo ------------------------------------------------------


#>>>>>>>>>> Steps to excecute your job goes here <<<<<<<<<<<<<<<<<<<<<

# Change to the temporary folder cretated for this job on the comp node
module load bedtools
cd /group/tran3/duytran/ngocduy.tran/Python\ scripts/continuous_merging
module load bedtools 

wget https://telentilab-dataset.s3.amazonaws.com/ncER/v2/Bin_1bp/ncER_perc_chr1_coordSorted.txt.gz
gunzip ncER_perc_chr1_coordSorted.txt.gz
mv ncER_perc_chr1_coordSorted.txt /group/tran3/duytran/ngocduy.tran/lift

cd ~
cd /group/tran3/duytran/ngocduy.tran/lift
chmod +x liftOver
./liftOver ncER_perc_chr1_coordSorted.txt hg19ToHg38.over.chain.gz ncer_transformed_chr1.bed unMapped

mv ncer_transformed_chr1.bed /group/tran3/duytran/ngocduy.tran/Python\ scripts/continuous_merging

cd ~
cd /group/tran3/duytran/ngocduy.tran/Python\ scripts/continuous_merging



#echo ------------------------------------------------------

exit
